python feat_distillation.py --distillation=nst_linear --layer=0 --student=ResNet18 --student_layer=10 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_e
python feat_distillation.py --distillation=nst_linear --layer=1 --student=ResNet18 --student_layer=23 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=nst_linear --layer=2 --student=ResNet18 --student_layer=35 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=nst_linear --layer=3 --student=ResNet18 --student_layer=46 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=0 --student=ResNet18 --student_layer=10 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=1 --student=ResNet18 --student_layer=23 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=2 --student=ResNet18 --student_layer=35 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=3 --student=ResNet18 --student_layer=46 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=0 --student=ResNet18 --student_layer=10 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=1 --student=ResNet18 --student_layer=23 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=2 --student=ResNet18 --student_layer=35 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=3 --student=ResNet18 --student_layer=46 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=0 --student=ResNet18 --student_layer=10 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=1 --student=ResNet18 --student_layer=23 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=2 --student=ResNet18 --student_layer=35 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=3 --student=ResNet18 --student_layer=46 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=0 --student=ResNet18 --student_layer=10 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=1 --student=ResNet18 --student_layer=23 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=2 --student=ResNet18 --student_layer=35 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=3 --student=ResNet18 --student_layer=46 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=nst_linear --layer=0 --student=MobileNet --student_layer=6 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=nst_linear --layer=1 --student=MobileNet --student_layer=15 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=nst_linear --layer=2 --student=MobileNet --student_layer=26 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=nst_linear --layer=3 --student=MobileNet --student_layer=55 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=0 --student=MobileNet --student_layer=6 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=1 --student=MobileNet --student_layer=15 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=2 --student=MobileNet --student_layer=26 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_mean --layer=3 --student=MobileNet --student_layer=55 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=0 --student=MobileNet --student_layer=6 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=1 --student=MobileNet --student_layer=15 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=2 --student=MobileNet --student_layer=26 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=att_max --layer=3 --student=MobileNet --student_layer=55 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=0 --student=MobileNet --student_layer=6 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=1 --student=MobileNet --student_layer=15 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=2 --student=MobileNet --student_layer=26 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=hint --layer=3 --student=MobileNet --student_layer=55 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=0 --student=MobileNet --student_layer=6 --teacher_layer=26 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=1 --student=MobileNet --student_layer=15 --teacher_layer=56 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=2 --student=MobileNet --student_layer=26 --teacher_layer=219 --dataset=GAN-Dataset --exp_name=GAN_exp
python feat_distillation.py --distillation=PKT --layer=3 --student=MobileNet --student_layer=55 --teacher_layer=239 --dataset=GAN-Dataset --exp_name=GAN_exp
