python kd_distillation.py --distillation=KD,T-1 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-5 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-10 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-50 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-100 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-1000 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-1 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-5 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-10 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-50 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-100 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-1000 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-1 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-5 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-10 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-50 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-100 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD,T-1000 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-1 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-5 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-10 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-50 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-100 --dataset=cifar10 --exp_name=KD_normal 
python kd_distillation.py --distillation=KD_CE,T-1000 --dataset=cifar10 --exp_name=KD_normal 
