python kd_distillation.py --student=ResNet18 --distillation=KD,T-1 --dataset=None --exp_name=KD_normal
python kd_distillation.py --student=ResNet18 --distillation=KD,T-5 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD,T-8 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD,T-10 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD,T-50 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD,T-100 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD_CE,T-1 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD_CE,T-5 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD_CE,T-8 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD_CE,T-10 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD_CE,T-50 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=ResNet18 --distillation=KD_CE,T-100 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD,T-1 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD,T-5 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD,T-8 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD,T-10 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD,T-50 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD,T-100 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD_CE,T-1 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD_CE,T-5 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD_CE,T-8 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD_CE,T-10 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD_CE,T-50 --dataset=None --exp_name=KD_normal 
python kd_distillation.py --student=MobileNet --distillation=KD_CE,T-100 --dataset=None --exp_name=KD_normal 
